title: AkuTrust
description: >
  AkuTrust merupakan platform berbasis AI yang dirancang untuk meningkatkan transparansi dan efisiensi dalam pengelolaan dana penataan dan rehabilitasi bangunan.
theme: jekyll-theme-cayman
