theme: Social
title: AkuTrust
description: AkuTrust merupakan platform berbasis AI yang dirancang untuk meningkatkan transparansi dan efisiensi dalam pengelolaan dana penataan dan rehabilitasi bangunan untuk mendorong perubahan sistematis dalam pengelolaan keuangan daerah otonom di Indonesia untuk meningkatkan efisiensi dan transparansi melalui penggunaan AkuTrust.


